#!/bin/bash
# Fresh Threads LLC - GitHub Projects Agile Setup Script

echo "🚀 Fresh Threads LLC - GitHub Projects Agile Setup"
echo "================================================="
echo ""
echo "📋 Setting up your professional project management system..."
echo ""

echo "🎯 STEP 1: Create Project Board"
echo "==============================="
echo "1. Go to: https://github.com/mooit-artist/FreshThreads/projects"
echo "2. Click: 'New project'"
echo "3. Select: 'Table view' (most Agile-friendly)"
echo "4. Name: 'Fresh Threads Agile Sprints'"
echo "5. Description: 'Agile sprint management for T-shirt business'"
echo ""

echo "🏃‍♂️ STEP 2: Configure Agile Workflow"
echo "=================================="
echo "Add these Status options (in order):"
echo "• 📦 Product Backlog"
echo "• 🎯 Sprint Backlog"
echo "• 🔄 In Progress"
echo "• 👀 Review"
echo "• ✅ Done"
echo "• 🚀 Released"
echo ""

echo "📊 STEP 3: Add Custom Fields"
echo "============================"
echo "Create these fields for Agile tracking:"
echo ""
echo "1. Story Points (Number):"
echo "   → 1 (Small task, <2 hours)"
echo "   → 2 (Medium task, 2-4 hours)"
echo "   → 3 (Large task, 4-8 hours)"
echo "   → 5 (Very large, 1+ days)"
echo ""
echo "2. Priority (Select):"
echo "   → 🔥 Critical"
echo "   → ⚡ High"
echo "   → 📋 Medium"
echo "   → 💭 Low"
echo ""
echo "3. Epic (Select):"
echo "   → 🏪 Business Foundation"
echo "   → 🎨 Product Development"
echo "   → 🌐 Website & Marketing"
echo "   → 📊 Analytics & Growth"
echo ""
echo "4. Sprint (Text):"
echo "   → Current sprint identifier (e.g., 'Sprint 1')"
echo ""

echo "📋 STEP 4: Create Initial User Stories"
echo "====================================="
echo "Add these starter issues to your project:"
echo ""

stories=(
    "🎨 Design first T-shirt concept and mockup"
    "🌐 Create basic business website/landing page"
    "📦 Research print-on-demand suppliers (Printful, Gooten)"
    "💳 Set up Stripe payment processing"
    "🏪 Choose and configure e-commerce platform"
    "📱 Set up business social media accounts"
    "📊 Configure Google Analytics and business tracking"
    "🎯 Define target customer personas"
    "💰 Create first T-shirt product listing"
    "📧 Set up email marketing system"
)

for i in "${!stories[@]}"; do
    echo "$((i+1)). ${stories[$i]}"
done

echo ""
echo "🎯 STEP 5: Plan Your First Sprint"
echo "================================="
echo "Sprint Goal: 'Launch Fresh Threads MVP'"
echo "Sprint Duration: 1 week (Aug 4-10, 2025)"
echo ""
echo "Select 3-5 user stories (5-8 story points total) for Sprint 1:"
echo "• Focus on highest business value"
echo "• Mix creative and technical work"
echo "• Keep it achievable for one person"
echo ""

echo "✅ SUCCESS CRITERIA:"
echo "==================="
echo "After setup you should have:"
echo "• ✅ GitHub Project board with Agile workflow"
echo "• ✅ 10+ user stories in Product Backlog"
echo "• ✅ Sprint 1 planned and ready to start"
echo "• ✅ Professional project management system"
echo ""

echo "🚀 Ready to set up your Agile project management!"
echo "Open: https://github.com/mooit-artist/FreshThreads/projects"
echo "Then follow the steps above! 📊"
