#!/bin/bash

# 🔒 FreshThreads Repository Security Cleanup
# This script secures the repository by removing exposed credentials

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔒 Starting Repository Security Cleanup${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Create backup directory
BACKUP_DIR="security-backup-$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo -e "${YELLOW}📦 Created backup directory: $BACKUP_DIR${NC}"

# Function to backup and secure file
secure_file() {
    local file_path=$1
    local description=$2

    if [ -f "$file_path" ]; then
        echo -e "${YELLOW}🔍 Securing: $description${NC}"

        # Backup original file
        cp "$file_path" "$BACKUP_DIR/$(basename "$file_path").backup"
        echo -e "${GREEN}✅ Backed up: $file_path${NC}"

        # Add to .gitignore if not already there
        if ! grep -q "$(basename "$file_path")" .gitignore 2>/dev/null; then
            echo "$(basename "$file_path")" >> .gitignore
            echo -e "${GREEN}✅ Added to .gitignore: $(basename "$file_path")${NC}"
        fi

        # Remove sensitive content
        case "$file_path" in
            *.params)
                echo "# PayPal credentials moved to GitHub Secrets" > "$file_path"
                echo "# Use: gh secret list to view configured secrets" >> "$file_path"
                ;;
            *.env)
                if [[ "$file_path" == *"paypal"* ]]; then
                    echo "# PayPal configuration generated from GitHub Secrets" > "$file_path"
                    echo "# This file is auto-generated by CI/CD pipeline" >> "$file_path"
                fi
                ;;
            *.html)
                # Replace hardcoded client ID with placeholder
                sed -i '' 's/client-id=AZ[a-zA-Z0-9_-]*/client-id=YOUR_PAYPAL_CLIENT_ID/g' "$file_path"
                echo -e "${GREEN}✅ Replaced hardcoded client ID with placeholder${NC}"
                ;;
        esac

        echo -e "${GREEN}✅ Secured: $file_path${NC}"
    else
        echo -e "${YELLOW}⚠️  File not found: $file_path${NC}"
    fi
}

# Secure PayPal credential files
echo -e "${BLUE}🔑 Securing PayPal Credentials${NC}"
secure_file "scripts/paypaldev.params" "PayPal developer parameters"
secure_file "config/paypal-config.env" "PayPal configuration file"

# Secure HTML files with hardcoded credentials
echo -e "${BLUE}🌐 Securing HTML Files${NC}"
secure_file "docs/paypal-checkout.html" "PayPal checkout page"

# Update .gitignore for sensitive patterns
echo -e "${BLUE}📝 Updating .gitignore${NC}"
cat >> .gitignore << 'EOF'

# Sensitive files
*.params
*config*.env
*secret*
*credential*
*key*
.env*
*token*

# Backup directories
security-backup-*
EOF

echo -e "${GREEN}✅ Updated .gitignore with sensitive file patterns${NC}"

# Create environment template
echo -e "${BLUE}📋 Creating Environment Template${NC}"
cat > config/paypal-config.env.template << 'EOF'
# PayPal Configuration Template
# Copy this file to paypal-config.env and fill in your credentials
# Never commit the actual config file - it should be in .gitignore

# PayPal API Credentials
PAYPAL_CLIENT_ID=your_client_id_here
PAYPAL_CLIENT_SECRET=your_client_secret_here
PAYPAL_ENVIRONMENT=sandbox
PAYPAL_BASE_URL=https://api-m.sandbox.paypal.com

# Business Information
PAYPAL_BUSINESS_EMAIL=your_business_email
BUSINESS_WEBSITE=https://your-website.com
PAYPAL_WEBHOOK_URL=https://your-website.com/api/paypal/webhook

# Additional Settings
PAYPAL_CURRENCY=USD
PAYPAL_INTENT=capture
PAYPAL_RETURN_URL=https://your-website.com/payment/success
PAYPAL_CANCEL_URL=https://your-website.com/payment/cancel
EOF

echo -e "${GREEN}✅ Created environment template: config/paypal-config.env.template${NC}"

# Check for any remaining exposed secrets
echo -e "${BLUE}🔍 Scanning for Remaining Exposed Secrets${NC}"
EXPOSED_SECRETS=0

# Check for PayPal patterns
if grep -r "AZ[a-zA-Z0-9_-]\{30,\}" --exclude-dir="$BACKUP_DIR" --exclude-dir=".git" . 2>/dev/null; then
    echo -e "${RED}❌ Found exposed PayPal Client IDs${NC}"
    EXPOSED_SECRETS=1
fi

if grep -r "EN[a-zA-Z0-9_-]\{30,\}" --exclude-dir="$BACKUP_DIR" --exclude-dir=".git" . 2>/dev/null; then
    echo -e "${RED}❌ Found exposed PayPal Secrets${NC}"
    EXPOSED_SECRETS=1
fi

# Check for any hardcoded emails that might be sensitive
if grep -r "bryan@freshthreadsllc.com" --exclude-dir="$BACKUP_DIR" --exclude-dir=".git" --exclude="*.md" . 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Business email found in code files (consider using environment variable)${NC}"
fi

# Report results
echo
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
if [ $EXPOSED_SECRETS -eq 0 ]; then
    echo -e "${GREEN}🎉 Repository Security Cleanup Complete!${NC}"
    echo -e "${GREEN}✅ No exposed secrets detected${NC}"
else
    echo -e "${RED}⚠️  Some secrets may still be exposed${NC}"
    echo -e "${YELLOW}Please review the output above and manually clean remaining items${NC}"
fi

echo
echo -e "${BLUE}📋 Next Steps:${NC}"
echo "1. Review backup files in: $BACKUP_DIR"
echo "2. Upload secrets to GitHub: ./scripts/upload_secrets_to_github.sh"
echo "3. Commit changes: git add . && git commit -m \"Secure repository: remove exposed credentials\""
echo "4. Configure GitHub Secrets for CI/CD"
echo
echo -e "${BLUE}🔗 Backup Location:${NC}"
echo "All original files backed up to: $BACKUP_DIR"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
